# deploy/helm/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: newrelic-secret
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  NEW_RELIC_LICENSE_KEY: {{ .Values.env.NEW_RELIC_LICENSE_KEY | b64enc }}