apiVersion: apps/v1
kind: Deployment
metadata:
  name: alerts-api
  labels:
    app: alerts
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alerts
  template:
    metadata:
      labels:
        app: alerts
    spec:
      containers:
        - name: alerts-api
          image: johnny711dock/alerts:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "secret"
            - name: DB_NAME
              value: "alerts"
            - name: GRPC_PORT
              value: "50051"
            - name: HTTP_PORT
              value: "8080"
