// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
)

type Alert struct {
	ID        int32        `json:"id"`
	AssetID   int32        `json:"asset_id"`
	Severity  string       `json:"severity"`
	CreatedAt sql.NullTime `json:"created_at"`
}
